language: node_js
node_js:
  - 0.10
  - 6
  - 8
  - 10
  - 11
before_install:
  - npm install -g qnit
  - npm install -g npm@2.15.0          # npm 5.6.0 removes ./node_modules and breaks the tests
after_success:
  - npm install -g nyc@8.4.0
  - npm install -g codecov coveralls
  - nyc --reporter lcov npm test && codecov
  - nyc report -r text-lcov | coveralls
