language: node_js
node_js:
  - 0.10
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
before_install:
  - npm install -g qnit
  - npm install -g npm@2.15.0          # npm 5.6.0 removes ./node_modules and breaks the tests
after_success:
  - npm install -g nyc@8.4.0
  - npm install -g codecov
  - nyc --reporter lcov npm test && codecov
